const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

function formatCurrency(value) {
    return `Rs ${Number(value).toFixed(2)}`;
}

function drawTableHeader(doc, y) {
    doc
        .fillColor("#0f172a")
        .fontSize(11)
        .text("Item", 52, y)
        .text("Qty", 320, y, { width: 50, align: "center" })
        .text("Unit Price", 380, y, { width: 80, align: "right" })
        .text("Line Total", 470, y, { width: 80, align: "right" });

    doc
        .moveTo(50, y + 16)
        .lineTo(545, y + 16)
        .strokeColor("#cbd5e1")
        .lineWidth(1)
        .stroke();

    return y + 26;
}

function generatePDF(invoice) {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const invoicePath = path.join(__dirname, "..", "invoices", `invoice_${invoice.id}.pdf`);
    doc.pipe(fs.createWriteStream(invoicePath));

    doc.rect(0, 0, doc.page.width, 116).fill("#0b3c5d");

    doc
        .fillColor("#f8fafc")
        .fontSize(11)
        .text(invoice.shopName || "Bill Maker Store", 50, 34, { align: "left" })
        .fontSize(22)
        .font("Helvetica-Bold")
        .text("TAX INVOICE", 50, 54)
        .font("Helvetica")
        .fontSize(11)
        .text(`Invoice #${invoice.id}`, 390, 46, { width: 155, align: "right" })
        .text(new Date(invoice.date).toLocaleString(), 390, 64, { width: 155, align: "right" });

    let y = 140;

    doc
        .fillColor("#0f172a")
        .fontSize(10)
        .text("Bill To", 50, y)
        .fontSize(11)
        .text("Walk-in Customer", 50, y + 16)
        .fontSize(10)
        .text(`Tax Rate: ${Number(invoice.taxRate || 0).toFixed(2)}%`, 50, y + 34);

    doc
        .roundedRect(360, y - 4, 185, 60, 8)
        .fillAndStroke("#f1f5f9", "#cbd5e1");

    doc
        .fillColor("#0f172a")
        .fontSize(10)
        .text("Amount Due", 376, y + 8)
        .font("Helvetica-Bold")
        .fontSize(17)
        .text(formatCurrency(invoice.total), 376, y + 25, { width: 152, align: "right" })
        .font("Helvetica");

    y = 240;
    y = drawTableHeader(doc, y);

    for (const item of invoice.items) {
        if (y > 730) {
            doc.addPage();
            y = 52;
            y = drawTableHeader(doc, y);
        }

        doc
            .fillColor("#1e293b")
            .fontSize(11)
            .text(item.name, 52, y, { width: 250 })
            .text(Number(item.quantity).toString(), 320, y, { width: 50, align: "center" })
            .text(formatCurrency(item.unitPrice), 380, y, { width: 80, align: "right" })
            .text(formatCurrency(item.total), 470, y, { width: 80, align: "right" });

        doc
            .moveTo(50, y + 18)
            .lineTo(545, y + 18)
            .strokeColor("#e2e8f0")
            .lineWidth(1)
            .stroke();

        y += 24;
    }

    y = Math.max(y + 16, 620);

    doc
        .fontSize(11)
        .fillColor("#334155")
        .text("Subtotal", 370, y, { width: 90, align: "right" })
        .text(formatCurrency(invoice.subtotal), 470, y, { width: 80, align: "right" })
        .text("Tax", 370, y + 20, { width: 90, align: "right" })
        .text(formatCurrency(invoice.tax), 470, y + 20, { width: 80, align: "right" });

    doc
        .moveTo(370, y + 42)
        .lineTo(545, y + 42)
        .strokeColor("#94a3b8")
        .lineWidth(1)
        .stroke();

    doc
        .font("Helvetica-Bold")
        .fillColor("#0f172a")
        .fontSize(12)
        .text("Total", 370, y + 52, { width: 90, align: "right" })
        .text(formatCurrency(invoice.total), 470, y + 52, { width: 80, align: "right" })
        .font("Helvetica");

    doc
        .fillColor("#64748b")
        .fontSize(9)
        .text("Thank you for your business.", 50, 772)
        .text("Generated by Bill Maker System", 390, 772, { width: 155, align: "right" });

    doc.end();
}

module.exports = generatePDF;
